# Generated by Django 4.2.9 on 2024-02-11 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('details', models.TextField(verbose_name='What to do')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
